# Generated by Django 3.1.6 on 2021-04-26 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='code',
        ),
        migrations.AddField(
            model_name='url',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=6, verbose_name='کلید')),
                ('target', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='url_shortener.url', verbose_name='مقصد')),
            ],
        ),
    ]
