# Generated by Django 3.1.6 on 2021-04-26 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_shortener', '0004_auto_20210426_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='slug',
            field=models.SlugField(max_length=6, unique=True, verbose_name='کلید'),
        ),
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده در'),
        ),
        migrations.AlterField(
            model_name='url',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile_images', verbose_name='تصویر نمایه')),
                ('birthdate', models.DateField(blank=True, verbose_name='تاریخ تولد')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
