# Generated by Django 3.1.6 on 2021-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0005_auto_20210427_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.CharField(choices=[('E', 'فعال'), ('D', 'غیر فعال')], default='E', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='url',
            name='جواد زاهدی',
            field=models.URLField(max_length=256, verbose_name='آدرس لینک'),
        ),
    ]
