# Generated by Django 3.1.6 on 2021-04-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0006_auto_20210427_0041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='جواد زاهدی',
            new_name='address',
        ),
    ]
