# Generated by Django 3.1.6 on 2021-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0008_url_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'verbose_name': 'URL'},
        ),
        migrations.AlterField(
            model_name='url',
            name='label',
            field=models.CharField(blank=True, max_length=128, verbose_name='برچسب'),
        ),
    ]
