# Generated by Django 3.1.6 on 2021-04-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0011_auto_20210427_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='visits',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدیدها'),
        ),
    ]
