# Generated by Django 3.1.6 on 2021-05-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0012_auto_20210427_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profile_images', verbose_name='تصویر نمایه'),
        ),
    ]
