# Generated by Django 3.1.6 on 2021-05-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0013_auto_20210501_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='status',
        ),
    ]
